version: "3.7"

services:
  image-analyzer:
    runtime: nvidia
    build:
      dockerfile: Dockerfile
      context: .
      args:
        INSTALL_SUFFIX: "-dev"
    environment:
      RABBITMQ_ENDPOINT: "amqp://admin:password@rabbitmq:5672"
      INPUT_ENDPOINT: "http://minio:9000"
      INPUT_TIMEOUT: "2"
      INPUT_MAX_ATTEMPTS: "5"
      AWS_ACCESS_KEY_ID: "admin"
      AWS_SECRET_ACCESS_KEY: "password"
    volumes:
      - ./:/opt/project/program
    networks:
      - main
networks:
  main:
    name: development
    external: true
