version: "3.7"

networks:
  main:
    name: development
    external: true

volumes:
  # https://docs.docker.com/storage/tmpfs/
  # https://stackoverflow.com/questions/41902930/docker-compose-tmpfs-not-working
  minio-data: null
#    driver_opts:
#      type: tmpfs
#      device: tmpfs
  rabbitmq-etc: null
  rabbitmq-data: null
  rabbitmq-logs: null

services:
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    depends_on:
      - minio-host
    networks:
      main:
        aliases:
          - minio

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-etc:/etc/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq/
      - ./config/rabbitmq-provision.sh:/rabbitmq-provision.sh
    networks:
      - main

  minio-host:
    image: minio/minio:RELEASE.2021-08-25T00-41-18Z
    command: server /data --console-address ":9001"
    expose:
      - "9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      #- MINIO_NOTIFY_AMQP_ENABLE1=on
      #- MINIO_NOTIFY_AMQP_URL1=amqp://admin:password@rabbitmq:5672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - rabbitmq
    volumes:
      - minio-data:/data
    networks:
      main: null

  minio-provision:
    image: minio/mc
    depends_on:
      - nginx
      - minio-host
    networks:
      main: null
    volumes:
      - "./config/minio-provision.sh:/minio-provision.sh"
    entrypoint: /minio-provision.sh

  minio-data-cleaner:
    image: minio/mc
    depends_on:
      - nginx
      - minio-host
    networks:
      main: null
    entrypoint: >
      /bin/sh -c "
        while true; do
          echo \"INFO: Sleeping\";
          sleep 10;
          /usr/bin/mc config host add myminio http://minio:9000 admin password;
          mc rm --recursive --dangerous --force --older-than 5m myminio/my-bucket/data/camera-capture;
        done
      "
